### ISSUE TITLE
 event callback is executed twice

### ISSUE THREAD

**Issue by zyxyuanxiao** [melvinkcx/fastapi-events#18]
Hello, I want to ask why the event callback is executed twice?

**Comment by zyxyuanxiao** [comment]
大佬，你好 为啥我注册事件之后，分派后，我们的事件回调执行了两次的呐？

**Comment by melvinkcx** [comment]
Is there any details you can provide? Which handler are you using?  Are you using wildcard `*`?

If you're using local_handler, please double check and make sure you are not registering multiple handlers with the same event name.

**Comment by zyxyuanxiao** [comment]
The example code is as follows:

from fastapi import FastAPI
from fastapi.requests import Request
from fastapi.responses import PlainTextResponse
from fastapi_events.dispatcher import dispatch
from fastapi_events.middleware import EventHandlerASGIMiddleware
from fastapi_events.handlers.local import local_handler
from fastapi_events.typing import Event

app = FastAPI()
app.add_middleware(EventHandlerASGIMiddleware,handlers=[local_handler])

@local_handler.register(event_name="my-fancy-event")
async def handle_all_events(event: Event):
    # event handlers can be coroutine function too (`async def`)
    pass
    print("注册的事件回调：",event)

@app.get("/")
async def index(request: Request) -> PlainTextResponse:
    # 开始分发事件！
    dispatch("my-fancy-event", payload={"id": 2})  # Emit events anywhere in your code
    return PlainTextResponse("你好")

if __name__ == '__main__':
    # 启动服务
    import uvicorn
    uvicorn.run('enevtmain:app', host='127.0.0.1', port=19085,reload=True, access_log=False, workers=1, use_colors=True)


-----
When accessing my request interface, the callback is used twice？

注册的事件回调： ('my-fancy-event', {'id': 2})
注册的事件回调： ('my-fancy-event', {'id': 2})

I'm sorry to trouble you~

**Comment by zyxyuanxiao** [comment]
I found the reason because: Number of times the function was added repeatedly

    def _register_handler(self, event_name, func):
        if not isinstance(event_name, str):
            event_name = str(event_name)

        if event_name not in self._registry:
            # 一个事件名称---存一个列表信息
            self._registry[event_name] = []
            self._registry_keycode= {}
        #一个事件名称
        if event_name not in self._registry_keycode.keys():
            self._registry_keycode[event_name] = event_name
            self._registry[event_name].append(func)

**Comment by melvinkcx** [comment]
Which version are you using? I can't reproduce it. 

Here is the code of the latest version registering handlers:

https://github.com/melvinkcx/fastapi-events/blob/b4da7e1b45d6a0f5ee6b052f6088ec4b4d381faf/fastapi_events/handlers/local.py#L38

The test cases covering local_handler are passing too

**Comment by melvinkcx** [comment]
@zyxyuanxiao hi, I played with your code a bit further. Here's the reason why your handler is registered twice:

When you run your script, let's say `main.py`:
```
python main.py
```

The lines before your `if __name__ == "__main__":` is executed, hence, your `handle_all_events` is registered. 

After that, when you run `uvicorn.run()`, the same file is loaded again, and your `handle_all_events` is being registered again (twice now).

```
# main.py

from fastapi import FastAPI
from fastapi.requests import Request
from fastapi.responses import PlainTextResponse

from fastapi_events.dispatcher import dispatch
from fastapi_events.handlers.local import local_handler
from fastapi_events.middleware import EventHandlerASGIMiddleware
from fastapi_events.typing import Event

app = FastAPI()
app.add_middleware(EventHandlerASGIMiddleware, handlers=[local_handler])


@local_handler.register(event_name="my-fancy-event")
async def handle_all_events(event: Event):
    print("注册的事件回调：", event)


@app.get("/")
async def index(request: Request) -> PlainTextResponse:
    dispatch("my-fancy-event", payload={"id": 2})  # Emit events anywhere in your code
    return PlainTextResponse("你好")


if __name__ == '__main__':
    # 启动服务
    import uvicorn

    uvicorn.run('server_18:app', host='127.0.0.1', port=19085, reload=True, access_log=False, workers=1,
                use_colors=True)

```

To fix it, you can try moving the lines before `if __name__ == "__main__" to a separate module. 

Tested locally, it works:
<img width="1401" alt="Screenshot 2021-12-18 at 11 21 59" src="https://user-images.githubusercontent.com/16914545/146625892-c0e5b583-d525-481e-aa5e-dd29210f6b19.png">

**Comment by zyxyuanxiao** [comment]
**Thank you very much for your answer ~ thank you**
