### ISSUE TITLE
Add a SNS Handler

### ISSUE THREAD

**Issue by andrewthetechie** [melvinkcx/fastapi-events#22]
The SQS handler is a good start, but it would be great if I could use fastapi events with SNS.

I know I could write a local handler or write my own handler, but it would be cool to see one included with fastapi-events.

**Comment by melvinkcx** [comment]
Hi @andrewthetechie, thanks for the request. I'm collecting insights on how developers use SNS. It'd be great if you could provide some feedback on this.

I'm thinking of a catch-all solution to forwarding all events to a particular SNS topic. Obviously, this wouldn't work for all use cases, but I think it's a good start.

**Comment by andrewthetechie** [comment]
That sort of catch-all would be a good first start, but I'd like to be able to route events to specific SNS topics, rather than just one topic. 

I'd be ok with having to define the topic by ARN.
