### ISSUE TITLE
Trigger an event at startup

### ISSUE THREAD

**Issue by ACassimiro** [melvinkcx/fastapi-events#27]
Is there a way to trigger an event at the startup of the application? I've been trying to do so with variations of the following piece of code:

 ```
app = FastAPI()
app.add_middleware(EventHandlerASGIMiddleware, 
                   handlers=[local_handler])
app.include_router(example.router)

@app.on_event("startup")
async def startup_event():
    dispatch("STARTING")
```

And I'm getting this error at the application startup:

```
ERROR:    Traceback (most recent call last):
  File "/home/acassimiro/Documents/tools/fastapi/eventDrivenApp/env/lib/python3.8/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/home/acassimiro/Documents/tools/fastapi/eventDrivenApp/env/lib/python3.8/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/home/acassimiro/Documents/tools/fastapi/eventDrivenApp/env/lib/python3.8/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/home/acassimiro/Documents/tools/fastapi/eventDrivenApp/main.py", line 39, in startup_event
    dispatch("STARTING")
  File "/home/acassimiro/Documents/tools/fastapi/eventDrivenApp/env/lib/python3.8/site-packages/fastapi_events/dispatcher.py", line 94, in dispatch
    return _dispatch(event_name=event_name, payload=payload)
  File "/home/acassimiro/Documents/tools/fastapi/eventDrivenApp/env/lib/python3.8/site-packages/fastapi_events/dispatcher.py", line 61, in _dispatch
    _dispatch_as_task(event_name, payload)
  File "/home/acassimiro/Documents/tools/fastapi/eventDrivenApp/env/lib/python3.8/site-packages/fastapi_events/dispatcher.py", line 37, in _dispatch_as_task
    handlers = _list_handlers()
  File "/home/acassimiro/Documents/tools/fastapi/eventDrivenApp/env/lib/python3.8/site-packages/fastapi_events/dispatcher.py", line 28, in _list_handlers
    middleware_id: int = middleware_identifier.get()
LookupError: <ContextVar name='fastapi_middleware_identifier' at 0x7fdbec69dd60>

ERROR:    Application startup failed. Exiting.
```

The task that I want to run with this starting event is supposed to dispatch events periodically, so even if I initially run it as a background task, I get the same error sometime after the application finishes starting. My current workaround is to manually call an endpoint that dispatches this event once the application is up and running, but I'd like to get rid of this step. 

By the way, thanks for the effort and work in this project.

**Comment by melvinkcx** [comment]
Hi @ACassimiro, thank you for reporting the issue. I am able to reproduce the bug.

## Some background of the design causing the issue 

During the instantiation of `EventHandlerASGIMiddleware`, the handlers are registered and stored in a global dictionary `fastapi_events.handler_store` with the middleware id as the key. This allows us to create multiple instances of middleware, each with different set of handlers, without them interfering with each other. This was initially designed to facilitate testing, but it has now become the crux of your issue.

When a request is being handled, the middleware sets another contextvar `middleware_identifier` to indicate which middleware (set of handlers) should be used if an event is dispatched during the handling of another event dispatched in the current context. This is to ensure the same set of handlers will be used to handle any subsequent events triggered in an event handler. Again, this is to provide isolation if multiple middleware instances are created.

As the startup event handler is triggered outside of a request-response cycle,  the `middleware_identifier` wouldn't have been set when your event is dispatched. Hence, you get the exception.

## Ideas

The solution that I can come up with so far, involves breaking changes. Here are some ideas:

1. We discard the need for a `middleware_identifier`. As a consequence, we will need to either find another way to support the isolation of handlers if multiple middleware are instantiated. I can't think of a good way to implement this other than what we have now. Any suggestions are welcome =)

2. We force the middleware to be a singleton. Instantiating multiple middleware will always get the same instance, this eliminates the need for the `middleware_identifier` contextvar. However, I think this is way too extreme.

3. Modify the `dispatch()` function to pick a default set of handlers from the `handler_store` if there is ONLY ONE set of handlers registered. If multiple sets of handlers are detected, we then have no good way to pick a set, an error should be raised. (Be reminded that a set of handlers is registered whenever a new middleware instance is created)

Maybe you have better ideas? Let me know what you think, thanks =)

**Comment by smithk86** [comment]
Hello, @melvinkcx!

I am running into this same issue. I have a background task that need to be able to dispatch events outside of the standard request context.

The current design has a lot of benefits. I think options 1 and 2 are out but 3 has promise though. What if there was the option to pass as user-defined id when creating the middleware? The `dispatch()` function could either accept this `id` and force the use that specified `handler_store` or, if not passed, use the current method of determining the `id` via the `ContextVar`.

```
def __init__(self, app: ASGIApp, handlers: Iterable[BaseEventHandler], middleware_id: Optional[int] = None) -> None:
        self.app = app
        self._id = id(self) if middleware_id is None else middleware_id
        self.register_handlers(handlers=handlers)
```

Cheers!
Kyle

**Comment by melvinkcx** [comment]
This issue is now resolved. Please refer to the [README](https://github.com/melvinkcx/fastapi-events#4-dispatching-events-outside-of-a-request) for the solution
