### ISSUE TITLE
TypeError with Synchronous Function in Dependencies When Using Local Handler

### ISSUE THREAD

**Issue by shulmaneyal** [melvinkcx/fastapi-events#60]
I've encountered a TypeError when a synchronous function is used as a dependency with the local event handler. It seems the dependency function is [expected to receive the event object](https://github.com/melvinkcx/fastapi-events/blob/dev/fastapi_events/handlers/local.py#L150) leading to a mismatch in arguments passed. Is this indeed intended?

Here's a snippet that reproduces the possible issue:
```python
@router.get("")
def status():
    dispatch("status")
    return {"status": "ok"}


def get_dependency():
    return "dependency"


@local_handler.register(event_name="*")
async def handle_all_events(event: Event, dependency=fastapi.Depends(get_dependency)):
    pass
```
This results in the following error:
`TypeError: get_dependency() takes 0 positional arguments but 1 was given`

Changing `get_dependency` signature to `async def get_dependency` runs successfully.

Thanks for this awesome library!

**Comment by melvinkcx** [comment]
hi, thanks for reporting this. I highly recommend using an async dependency, but I'll double check if sync dependencies are supposed to be supported in fastapi

**Comment by shulmaneyal** [comment]
Thanks for the quick reply. Just to provide more color on this, we currently use Depends to reuse db queries or other operations that might be async. But also for dependency injection, for which we usually don't need them to be async, something like the below
```
def get_repository() -> Repository:
    return Repository()

def get_service(repository=Depends(get_repository)) -> Service:
    return Service(repository=repository)
```

**Comment by shulmaneyal** [comment]
Thanks! @melvinkcx
