### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by ediskandarov-cur** [melvinkcx/fastapi-events#7]
https://github.com/melvinkcx/fastapi-events/blob/a5a2823a183756c2c922cf90ac35afa8e1544d79/fastapi_events/middleware.py#L23-L28

```python
        token: Token = event_store.set(deque())
        try:
            await self.app(scope, receive, send)
        finally:
            await self._process_events()
        event_store.reset(token)
```

If `await self._process_events()` raises an exception then `event_store.reset(token)` does not happen.

**Comment by melvinkcx** [comment]
I agree with you, since we're using `.reset()` here, we should do it properly instead of relying on GC to clean it up in case of any exceptions
